[package]
name = "sort_afterhours"
author = "Nestor Wheelock"
license = "GNU GPLv3"
description = "Sorts files created during afterhours"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
